package cn.datacraft.atcoder;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpHeaders;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.net.ssl.SSLSession;
import java.util.zip.GZIPOutputStream;

import static org.assertj.core.api.Assertions.assertThat;

class AtcoderStandingsClientTest {
    @Test
    void recognizesCloudFrontRequestBlockAsNetworkFailure() {
        HttpResponse<String> response = response(403,
                "<h2>The request could not be satisfied.</h2><p>Request blocked.</p>Generated by cloudfront");

        assertThat(AtcoderStandingsClient.isEdgeBlocked(response)).isTrue();
    }

    @Test
    void doesNotTreatEveryForbiddenResponseAsCloudFrontBlock() {
        assertThat(AtcoderStandingsClient.isEdgeBlocked(response(403, "Forbidden"))).isFalse();
        assertThat(AtcoderStandingsClient.isEdgeBlocked(response(200, "Request blocked"))).isFalse();
    }

    @Test
    void decodesGzipResponseBody() throws Exception {
        byte[] compressed;
        try (ByteArrayOutputStream bytes = new ByteArrayOutputStream();
             GZIPOutputStream gzip = new GZIPOutputStream(bytes)) {
            gzip.write("榜单数据".getBytes(java.nio.charset.StandardCharsets.UTF_8));
            gzip.finish();
            compressed = bytes.toByteArray();
        }
        HttpHeaders headers = HttpHeaders.of(Map.of("Content-Encoding", List.of("gzip")),
                (name, value) -> true);

        assertThat(AtcoderStandingsClient.decodeBody(headers, compressed)).isEqualTo("榜单数据");
    }

    private static HttpResponse<String> response(int status, String body) {
        return new HttpResponse<>() {
            @Override public int statusCode() { return status; }
            @Override public HttpRequest request() { return null; }
            @Override public Optional<HttpResponse<String>> previousResponse() { return Optional.empty(); }
            @Override public HttpHeaders headers() { return HttpHeaders.of(Map.of(), (name, value) -> true); }
            @Override public String body() { return body; }
            @Override public Optional<SSLSession> sslSession() { return Optional.empty(); }
            @Override public URI uri() { return URI.create("https://atcoder.jp/settings"); }
            @Override public HttpClient.Version version() { return HttpClient.Version.HTTP_2; }
        };
    }
}
