CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(40) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(16) NOT NULL,
    enabled BOOLEAN NOT NULL,
    daily_generation_limit INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE generation_jobs (
    id VARCHAR(36) PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_accounts(id),
    status VARCHAR(32) NOT NULL,
    progress INTEGER NOT NULL,
    message VARCHAR(500),
    error TEXT,
    statement TEXT NOT NULL,
    standard_code TEXT NOT NULL,
    requirements TEXT NOT NULL,
    case_count INTEGER NOT NULL,
    cpp_standard VARCHAR(12),
    plan_json TEXT,
    artifact_path VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_generation_jobs_user_created
    ON generation_jobs (user_id, created_at DESC);

CREATE TABLE ai_config (
    id BIGINT PRIMARY KEY,
    base_url VARCHAR(500),
    model VARCHAR(120),
    encrypted_api_key TEXT,
    daily_generation_limit INTEGER,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE typing_articles (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    category VARCHAR(12) NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE typing_article_seed_state (
    id VARCHAR(40) PRIMARY KEY,
    initialized_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE legacy_imports (
    source_sha256 VARCHAR(64) PRIMARY KEY,
    source_file VARCHAR(500) NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    row_counts TEXT NOT NULL,
    row_hashes TEXT NOT NULL
);
