CREATE TABLE atcoder_leaderboard_config (
    id BIGINT PRIMARY KEY,
    contest_id VARCHAR(64) NOT NULL,
    display_title VARCHAR(160) NOT NULL,
    official_title VARCHAR(240) NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE,
    end_at TIMESTAMP WITH TIME ZONE,
    tasks_json TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE atcoder_leaderboard_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(40) NOT NULL,
    atcoder_username VARCHAR(32) NOT NULL,
    atcoder_username_key VARCHAR(32) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_atcoder_leaderboard_participants_order
    ON atcoder_leaderboard_participants (sort_order, id);
