CREATE TABLE atcoder_problem_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contest_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    task_label VARCHAR(16) NOT NULL,
    task_name VARCHAR(240) NOT NULL,
    task_order INTEGER NOT NULL,
    source_html TEXT,
    translated_html TEXT,
    status VARCHAR(24) NOT NULL,
    error_message TEXT,
    source_fetched_at TIMESTAMP WITH TIME ZONE,
    translated_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_atcoder_problem_translation_task UNIQUE (contest_id, task_id)
);

CREATE INDEX idx_atcoder_problem_translation_order
    ON atcoder_problem_translations (contest_id, task_order, id);
